google_adsense: ca-pub-7827859788508375

microsoft_clarity:
  id: jqz81bklca

hb:
  blog:
    giscus:
      repo: hugomods/site
      repo_id: R_kgDOJLF7dg
      category: General
      category_id: DIC_kwDOJLF7ds4CVB4a
      mapping: url
  docs:
    giscus:
      repo: hugomods/site
      repo_id: R_kgDOJLF7dg
      category: General
      category_id: DIC_kwDOJLF7ds4CVB4a
      mapping: url
