pwa:
  debug: false
  caches:
    font:
      strategy: network-first
    image:
      strategy: network-first
    script:
      strategy: network-first
    style:
      strategy: network-first

decap_cms:
  local_backend: true
