hb:
  header:
    main_brand:
    # git_org:
    #   service: github
    #   name: hugomods
  footer:
    site_copyright: ''
    site_description: ''
  blog:
    sidebar:
      profile:
        company: "[HugoMods](https://github.com/hugomods)"
        location: Internet
        socials:
          github: hugomods
          githubsponsors: https://github.com/sponsors/razonyang
          mastodon: https://techhub.social/@hugomods
          paypal: razonyang
          rss: true
  # docs:
    # navs_active_style: bordered
  content_panel:
    repo:
      subpath: home
