outputs:
  home:
    - DecapCMSConfig
    - HTML
    - Offline
    - SearchIndex
    - RSS
    - WebAppManifest

taxonomies:
  _merge: shallow

markup:
  _merge: deep

build:
  _merge: shallow

caches:
  _merge: deep

menus:
  _merge: deep

module:
  imports:
    - path: github.com/hugomods/site/common

params:
  hb:
    header:
      logo: false
      brand: Decap CMS
      git_repo:
        service: github
        owner: hugomods
        name: decap-cms
    content_panel:
      repo:
        subpath: decap-cms

baseURL: https://decap-cms.hugomods.com/

languages:
  _merge: deep

  en:
    title: Hugo Decap CMS Module | HugoMods
    # baseURL: https://decap-cms.hugomods.com/
    params:
      description: Hugo module to help developers and users integrate Decap CMS (formerly Netlify CMS) with their themes and sites easilly.
      hb:
        footer:
          site_title: HugoMods
          site_description: Third party Hugo modules and tools for building fast, modular, modern themes and static websites.

  zh-hans:
    title: Hugo Decap CMS 模块 | HugoMods
    # baseURL: https://zh-hans.decap-cms.hugomods.com/
    params:
      description: 用于帮助开发人员和用户轻松地将 Decap CMS（前身 Netlify CMS）与他们的主题和站点集成起来的模块。
      hb:
        footer:
          site_title: HugoMods
          site_description: 

  zh-hant:
    title: Hugo Decap CMS 模塊 | HugoMods
    # baseURL: https://zh-hant.decap-cms.hugomods.com/
    params:
      description: 用於幫助開發人員和用戶輕鬆地將 Decap CMS（前身 Netlify CMS）與他們的主題和站點集成起來的模塊。
      hb:
        footer:
          site_title: HugoMods
          site_description: Third party Hugo modules and tools for building fast, modular, modern themes and static websites.

security:
  _merge: deep

server:
  _merge: deep
